// Code generated by "stringer -type ActionStatus interface.go"; DO NOT EDIT.

package action

import "fmt"

const _ActionState_name = "UNKNOWNSUCCESSFAILED"

var _ActionState_index = [...]uint8{0, 7, 14, 20}

func (i ActionState) String() string {
	if i < 0 || i >= ActionState(len(_ActionState_index)-1) {
		return fmt.Sprintf("ActionState(%d)", i)
	}
	return _ActionState_name[_ActionState_index[i]:_ActionState_index[i+1]]
}
